# Site settings
title: P4N4Rd1
description: '- CERT Security Analyst -'
url: 'http://zemelusa.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Zemelusa'
  email: zemelusa@gmail.com
  twitter_username: zemelusa
  github_username:  zemelusa
  linkedin_username: panardin
  medium_username: zemelusa
  keybase_username: panardin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']