# Site settings
title: Zemelusa
description: Some tricks and tips to solve CTF challenges and learn about Ethical Hacking
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://zemelusa.github.io/" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: Zemelusa #github username
repo: zemelusa.github.io #github repository
branch: master #branch
production_url:  https://zemelusa.github.io/
source_url:  https://github.com/zemelusa/zemelusa.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
